#index:
#    path: /
#    controller: App\Controller\DefaultController::index

product.index:
  path: /product
  controller: App\Controller\ProductController:index

product.show:
    path: /product/{id}
    controller: App\Controller\ProductController::show